### ISSUE TITLE
[Question] moving center c_i and almost zero delta_cs

### ISSUE THREAD

**Issue by saprrow** [WangLongZJU/DeepAC#17]
Hi, thanks for your great work and I found it works in practice.
But I am troubled by a problem. Your paper mentions that the center c_i is unmoved, as shown below.
![Screenshot from 2024-05-28 14-41-06](https://github.com/WangLongZJU/DeepAC/assets/44662300/a04bd770-f330-4c22-a689-3dd4f3536513)

However I found that the c_i is updated with `deformed_body2view_pose_data`. And the projected contour point is also calculated from `body2view_pose_data`. Actually, `deformed_body2view_pose_data` equals to `body2view_pose_data`, so the projected difference di(delta_cs) is almost zero. 
![Screenshot from 2024-05-28 14-47-11](https://github.com/WangLongZJU/DeepAC/assets/44662300/fa4a91c8-1063-42fa-bbd6-d64b4c1ce725)
![Screenshot from 2024-05-28 14-47-56](https://github.com/WangLongZJU/DeepAC/assets/44662300/85e6beda-66c2-492b-946f-f36b9ea5de4a)

Could you help me with my confusion?

**Comment by WangLongZJU** [comment]
Yes, in our pytorch code, the c_i is updated with the current object pose deformed_body2view_pose_data and the projected difference d_i is zero. Because we want the best performance.

You can use the previous object pose to compute the c_i and the d_i to optimize the object pose. This way can improve the efficiency. Especially on a mobile device, it can reduce computational complexity with only a slight decrease in accuracy.

**Comment by saprrow** [comment]
@WangLongZJU  My confusion is gone. Thanks for your super fast reply！
